language: cpp
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - os: osx
      osx_image: xcode 8.3
script: ./build.sh

